version: '3'
services:
  nodejs-app:
    build: .
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  redis:
    image: redis
    ports:
      - 6379:6379                